[workspace]
resolver = "3"
members = ["crates/arams-wasm", "crates/arams-cli", "crates/arams-core"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/chfuchte/arams"

[workspace.dependencies]
arams-core = { path = "crates/arams-core" }
